language: c
compiler: gcc
dist: xenial

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Fe8UzmvOO2YIAt5YEa2IKaPnD5lzbuIVZfiAneDQPOxP9FxyL6HxmVtblRFkddaTRxFqPnC0DNnFa20+D/VwxoljjL9USXbaXvuonwRWQ8ujCFm2aymmrxpbHLmD+n3n5OlvMG2zM/xWbn+3G53UHJ5DO8NS3GZEICzWiPHWQkfrHvCKrH46Z0WaqiSwP9+VEgIK+QTBOARzKXhmwswf5CUhBy9u64UoXZGXebtDlR24q1GjBoh0hz4nYhTpq9PlgfLDCK18uA7xsVQ2J/223NE0u91J2ucf1Yb+oMs/MQBr58UuvxUBNMETXwwUXfInrpWCYA3mgFECK24Xc+mNXDJ4LBSPe9Vkjezv8+qoO6nhrrK9z9UchPmydMbLbDvJUDZFoI0mSfgkpEJfPN5zX5LGMypSEF+y2EbT27AwJa2BYMKHa3aYax6Ds7x5fgSZp5T0+gSxT3KPvCSBriMOisqdQDTshwbNUiN9vndkHh0cfCBZ3CcDyXEGMFVIWnq0n7mvtitMMgQA6DGhqnhDoDZXelLh39lwSwgdTpxje7ZEN6cAOyzoVwdIwkHJizfjrWyf7hfufi2rclmkU/oCG+d2QNdLHq9VMVVhUqFQvBPJAY94NKzemdjCLfb9j1KddU5vYZ5HclZrxyZaQGKPLSFR1Nnz9FzGZLr14uc1Rq4="
   - CROSS_COMPILE="/tmp/gcc-linaro-7.3.1-2018.05-x86_64_arm-eabi/bin/arm-eabi-"
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - sudo apt install libcunit1-dev qemu-system-arm curl git u-boot-tools uuid-dev libusb-1.0-0-dev libtool-bin
  - curl -sL https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-eabi/gcc-linaro-7.3.1-2018.05-x86_64_arm-eabi.tar.xz | tar xJ -C /tmp
  - git clone --branch v1.0.1 https://github.com/libtom/libtommath.git
  - make -C libtommath -f makefile.shared
  - sudo make -C libtommath -f makefile.shared PREFIX=/usr install
  - git clone --branch v1.18.2 https://github.com/libtom/libtomcrypt.git
  - make -C libtomcrypt -f makefile.shared CFLAGS="-DUSE_LTM -DLTM_DESC" EXTRALIBS="-ltommath"
  - sudo make -C libtomcrypt -f makefile.shared PREFIX=/usr install

addons:
  apt:
    update: true
  coverity_scan:
    project:
      name: "jonpe960/punchboot"
      description: "Build submitted via Travis CI"
    notification_email: jonpe960@gmail.com
    build_command_prepend: "cov-configure --comptype gcc --compiler arm-eabi-gcc --template"
    build_command:   "make"
    branch_pattern: "coverity"

script:
    - make
jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - bash <(curl -s https://codecov.io/bash)
